### ISSUE TITLE
About the total epoch

### ISSUE THREAD

**Issue by xy-guo** [DeepMotionAIResearch/DenseMatchingBenchmark#12]
Thank you for your excellent work! When I check the number of epochs in the AcfNet configs for training on SceneFlow dataset, I found total_epochs is 20, but the checkpoint is set to epoch_10.pth. May I ask how many epochs the network is trained for the final paper results? Thank you so much!

**Comment by youmi-zym** [comment]
Hi, @xy-guo ,
As the paper claimed, for a fair comparison with other state-of-the-art stereo matching methods on scene_flow, we only trained 10 epochs, the corresponding checkpoint is [here: 10 epochs](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/configs/AcfNet/ResultOfAcfNet.md#10-epoch). But for submission on KITTI, we further trained 20 epochs and the corresponding checkpoint is [here: 20 epochs](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/configs/AcfNet/ResultOfAcfNet.md#20-epoch)

**Comment by xy-guo** [comment]
Thank you so much!
