### ISSUE TITLE
"bash INSTALL.sh dcn" error

### ISSUE THREAD

**Issue by jingfenglanyun** [DeepMotionAIResearch/DenseMatchingBenchmark#15]
**ENV: python3.7 + torch1.5 + cuda10.2** 

**error message:**
....
/deform_conv_cuda.cpp:66:3: error: ‘AT_CHECK’ was not declared in this scope
.......
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/seiriosai/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/seiriosai/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 14, in <module>
.....
RuntimeError: Error compiling objects for extension
cp: 无法获取'build/lib*' 的文件状态(stat): 没有那个文件或目录

**Comment by jingfenglanyun** [comment]
This error is solved by replace "AT_CHECK" to "TORCH_CHECK" in "dmb.ops.dcn.src.deform_conv_cuda.cpp" and "dmb.ops.dcn.src.deform_pool_cuda.cpp".
Reference link [https://github.com/open-mmlab/mmdetection/issues/2513](url)

**Comment by youmi-zym** [comment]
Thanks, got your problem. I find it only happens when using torch1.5, but it's fine for other versions.

**Comment by moha23** [comment]
@jingfenglanyun @youmi-zym 

> This error is solved by replace "AT_CHECK" to "TORCH_CHECK" in "dmb.ops.dcn.src.deform_conv_cuda.cpp" and "dmb.ops.dcn.src.deform_pool_cuda.cpp".
> Reference link [https://github.com/open-mmlab/mmdetection/issues/2513](url)

The reference link isn't working, where do I find these files?
