### ISSUE TITLE
ImportError: cannot import name 'get_world_size'

### ISSUE THREAD

**Issue by amaanda** [DeepMotionAIResearch/DenseMatchingBenchmark#16]
I was able to successfully install the module, but when running the inference.py script I get this error. Any hints on what might be causing this?

Python 3.6
Torch 1.2.0
Windows 10

**Comment by youmi-zym** [comment]
Hi, @amaanda 
Please copy the whole printed error info here. I still cannot judge the problem...

**Comment by amaanda** [comment]
Thanks for the quick response!
I read about torch.distributed on pytorch and apparently it's just for training?
```
Traceback (most recent call last):
  File ".\inference.py", line 16, in <module>
    from dmb.data.transforms import stereo_trans as T
  File "d:\tarefas\dezembro\densematchingbenchmark\dmb\data\__init__.py", line 1, in <module>
    from .loaders import build_data_loader
  File "d:\tarefas\dezembro\densematchingbenchmark\dmb\data\loaders\__init__.py", line 1, in <module>
    from .builder import build_data_loader
  File "d:\tarefas\dezembro\densematchingbenchmark\dmb\data\loaders\builder.py", line 8, in <module>
    from .samplers import GroupSampler, DistributedGroupSampler, DistributedSampler
  File "d:\tarefas\dezembro\densematchingbenchmark\dmb\data\loaders\samplers.py", line 7, in <module>
    from torch.distributed import get_world_size, get_rank
ImportError: cannot import name 'get_world_size'
```

**Comment by youmi-zym** [comment]
Hi, @amaanda 
if you use our developed [Inference API](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/dmb/apis/inference.py), you don't need to build a data loader, as only the path of images is needed, you can check [here](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/dmb/apis/inference.py#L98).

I have also checked the code 
```python 
from torch.distributed import get_world_size, get_rank
```
It runs ok with torch=1.2.0. 
So, I'm afraid you have to try again and find out the behind reason.

**Comment by amaanda** [comment]
I am using torch=1.2.0 but for some reason when I run `torch.distributed.is_available()` i get `False`. I simply commented out the line you mentioned and the code seems to be working fine.

```
>>> import torch
>>> torch.distributed.is_available()
False
>>> torch.__version__
'1.2.0'
```

**Comment by youmi-zym** [comment]
Hi, @amaanda 
I guess it's something wrong with the cudatoolkit or backend. You can google `torch.distributed.is_available()=False` to solve your problem.

By the way, it runs ok for me:

![image](https://user-images.githubusercontent.com/17737537/81243668-12275e80-9043-11ea-882c-115cd88d1bba.png)

**Comment by amaanda** [comment]
Yeah, probably. I did try some solutions I found, will try some more. Thanks! :)
