### ISSUE TITLE
missing of annotations/full_train.json

### ISSUE THREAD

**Issue by laosiji123456** [DeepMotionAIResearch/DenseMatchingBenchmark#4]
Nice job! But I can't find the file annotations/full_train.json.
Thansk a lot!

**Comment by Minwellcym** [comment]
You can generate the json files by these two files : https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/tools/datasets/gen_kitti2015_anns.py
https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/tools/datasets/gen_sceneflow_anns.py

`python tools/datasets/gen_sceneflow_anns.py --data-root DIR_TO_SCENEFLOW --save-annotation-root DIR_TO_SCENEFLOW/annotations`
I will add this to DATA.md later.
