### ISSUE TITLE
a little question about data augmentation

### ISSUE THREAD

**Issue by chenglong0313** [DeepMotionAIResearch/DenseMatchingBenchmark#6]
How much can data augmentation  improve performance in your view? Are there any plan to add some other data augmentation methods， not only crop.

**Comment by youmi-zym** [comment]
In our setting, we only include cropping, normalization as our data augmentation. We have ever tried with resizing, but the worse result got. Thus we haven't tried any data augmentation more. I think data augmentation is really good way to solve some difficult problems and we're exploring. If you have some good data augmentation methods, we're very welcome.

**Comment by chenglong0313** [comment]
Thanks a lot.
