### ISSUE TITLE
how to get the F and B in kitti2015

### ISSUE THREAD

**Issue by chenglong0313** [DeepMotionAIResearch/DenseMatchingBenchmark#8]
Can you tell me how to parse the calibration files to get the F and B in kitti2015？Thanks a lot.

**Comment by youmi-zym** [comment]
Hi, @chenglong0313 
You mean baseline b, focal length f?
The baseline b=0.54 in Kitti
As for focal length, it corresponds to the first number of  P_rect_0x in calibration files, where x is the camera id. i.e. f=721.5377

**Comment by chenglong0313** [comment]
Thanks  a lot. 

I just searched in github again， then I find it here. 
https://github.com/mrharicot/monodepth/blob/b76bee4bd12610b482163871b7ff93e931cb5331/utils/evaluation_utils.py#L146

OK, the focal length is the same as your. 
Baseline is a little different, but almost the same
